### ISSUE TITLE
Could there be an example .gitolite.rc file in /docs

### ISSUE THREAD

**Issue by issackelly** [stephrdev/brigitte#1]
Also, how are you updating the repo list for gitolite?  My first thought was a post-save signal that would evoke some script.

**Comment by stephrdev** [comment]
working on it. I'm thinking of a celery based message queue (also for post-commit hooks/processing).

gitolite config and docs will follow soon.

**Comment by issackelly** [comment]
Std gitolite config with your instructions works perfectly.  I've got mine setup.  Cheers
